postprocessor_args:
  n_clusters: 96
  alpha: 0.05
  method: soft-kmeans
  n_classes: 10
  clustering_seed: 0
  init_scheme: kmeans
  n_init: 5
  space : probits
  temperature: 4.9
  cov_type: diag
  reorder_embs: True
  bound: hoeffding
  pred_weights: 0
experience_args:
  n_folds: 3
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test

  # File: transform-test_n-epoch1_n-folds10_probits_predweight_clustering
