name: msp
postprocessor_args:
  magnitude: 0
  temperature: 1
experience_args:
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test
ablation_args:
  temperature: [1, 1.5, 2, 2.5, 3, 3.5, 4, 7, 8, 9, 10]