postprocessor_args:
  n_clusters: 80
  alpha: 0.05
  method: soft-kmeans
  n_classes: 10
  clustering_seed: 0
  init_scheme: kmeans
  n_init: 5
  space : probits
  temperature: 1.2
  cov_type: diag
  reorder_embs: True
  bound: hoeffding
  pred_weights: 0.001
postprocessor_grid:
  pred_weights: [0., 0.0005, 0.001, 0.0015, 0.002, 0.0025, 0.003, 0.0035, 0.004, 0.0045]
experience_args:
  n_folds: 3
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test
  
# File: cifar100_densenet121_r-2_seed-split-9/transform-test_n-epoch1_n-folds10_probits_predweight_clustering