postprocessor_args:
  n_clusters: 88
  alpha: 0.05
  method: soft-kmeans
  n_classes: 10
  clustering_seed: 0
  init_scheme: kmeans
  n_init: 5
  space : probits
  temperature: 7.3
  cov_type: diag
  reorder_embs: True
  bound: hoeffding
  pred_weights: 0.0025
postprocessor_grid:
  temperature: [6.7, 6.9, 7.1, 7.3, 7.5, 7.7, 7.9, 8.1, 8.3]
  n_clusters: [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]
  pred_weights: [0., 0.0005, 0.001, 0.0015, 0.002, 0.0025, 0.003, 0.0035, 0.004, 0.0045]
experience_args:
  n_folds: 3
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test

# File: cifar10_resnet34_r-2_seed-split-9/transform-test_n-epoch1_n-folds10_probits_probweights_clustering
