postprocessor_args:
  n_clusters: 80
  alpha: 0.05
  method: soft-kmeans_torch
  n_classes: 100
  clustering_seed: 0
  init_scheme: kmeans
  n_init: 5
  space : probits
  temperature: 1.2
  cov_type: diag
  reorder_embs: True
  bound: hoeffding
  pred_weights: 0.001
experience_args:
  n_folds: 3
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test
ablation_args:
  temperature: [4.7, 4.9, 5.1, 5.3, 5.5, 5.7, 5.9, 6.1, 6.3]
  n_clusters: [60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]
  

