postprocessor_args:
  n_clusters: 96
  alpha: 0.05
  method: soft-kmeans
  n_classes: 10
  clustering_seed: 0
  init_scheme: kmeans
  n_init: 5
  space : probits
  temperature: 4.9
  cov_type: diag
  reorder_embs: True
  bound: hoeffding
  pred_weights: 0
postprocessor_grid:
  temperature: [4.7, 4.9, 5.1, 5.3, 5.5, 5.7, 5.9, 6.1, 6.3]
  n_clusters: [90, 92, 94, 96, 98, 100, 102, 104, 106, 108]
  pred_weights: [0., 0.0005, 0.001, 0.0015, 0.002, 0.0025, 0.003, 0.0035, 0.004, 0.0045] # Don't need this
experience_args:
  n_folds: 3
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test

# File: cifar10_densenet121_r-2_seed-split-9/transform-test_n-epoch1_n-folds10_probits_predweight_clustering/hyperparams_results.csv
