name: partition
postprocessor_args:
  alpha: 0.05
  method: soft-kmeans_torch
  bound: bernstein
  n_classes: 100

  space : probits
  reorder_embs: True
  temperature: 1.
  pred_weights: 0
  
  n_clusters: 78
  init_scheme: random
  n_init: 100
  max_iter: 100
  clustering_seed: 1
  calibrate: True
  
  
experience_args:
  ratio_res_split: 1
  n_split_val : 1
  weight_std : 0
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test

postprocessor_grid:
  n_clusters: [100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330]
  temperature: [1]
