name: partition
postprocessor_args:
  alpha: 0.05
  method: soft-kmeans_torch
  bound: bernstein
  n_classes: 100

  space : probits
  reorder_embs: True
  temperature: 1.
  pred_weights: 0
  
  n_clusters: 78
  init_scheme: random
  n_init: 100
  max_iter: 100
  clustering_seed: 0
  calibrate: True
  
  
experience_args:
  ratio_res_split: 1
  n_split_val : 1
  weight_std : 0
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test

postprocessor_grid:
  n_clusters: [ 25, 30, 35, 40, 45, 55, 60, 65, 70, 75]
  temperature: [2]
