name: unif-mass
postprocessor_args:
  method: unif-mass
  n_clusters: 30
  alpha: 0.05
  bound: hoeffding
  score: upper  # Use upper CI bound as the score
  space: margin
  temperature: 1.0
  normalize: false
  magnitude: 0.0
  n_classes: 100
  reorder_embs: True
  pred_weights: 0
  init_scheme: None
  n_init: None
  max_iter: None
  clustering_seed: None

experience_args:
  n_folds: None
  fit_after_cv: False
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test

postprocessor_grid:
  n_clusters: [10, 20, 30, 50, 100]
  alpha: [0.01, 0.05, 0.1]
  score: [upper, mean]
