name: partition
postprocessor_args:
  alpha: 0.05
  method: soft-kmeans_torch
  bound: bernstein
  n_classes: 10

  space : probits
  reorder_embs: True
  temperature: 2
  pred_weights: 0
  
  n_clusters: 100
  init_scheme: kmeans
  n_init: 1000
  max_iter: 300
  clustering_seed: 1
  
experience_args:
  ratio_res_split: 0.52
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test

postprocessor_grid:
  n_clusters: [70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
