name: random_forest
postprocessor_args:
  temperature: 2
  space: probits
  reorder_embs: True

  n_estimators: 100
  max_depth: 3
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: sqrt
  random_state: 1
  class_weight: balanced
experience_args:
  n_folds: 5
  n_epochs:
    res: None
    cal: 1
  transform:
    res: None
    cal: test
postprocessor_grid:
    n_estimators: [150, 170, 190, 210, 220, 230, 250, 270, 300] # [50, 100, 200] 
    max_depth: [3, 5, 10]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    
  # File: transform-test_n-epoch1_n-folds10_probits_predweight_clustering
