name: random_forest
postprocessor_args:
  temperature: 2
  space: probits
  reorder_embs: True

  n_estimators: 100
  max_depth: 3
  min_samples_split: 10
  min_samples_leaf: 4
  max_features: sqrt
  random_state: 1
  class_weight: balanced
experience_args:
  n_folds: 5
  n_epochs:
    res: None
    cal: 1
  transform:
    res: None
    cal: test
    
  # File: transform-test_n-epoch1_n-folds10_probits_predweight_clustering
