name: random_forest
postprocessor_args:
  temperature: 2
  space: probits
  reorder_embs: True

  n_estimators: 100
  max_depth: 9
  min_samples_split: 2
  min_samples_leaf: 100
  max_features: log2
  random_state: 1
  criterion: gini
  class_weight: balanced
experience_args:
  n_folds: 5
  n_epochs:
    res: None
    cal: 1
  transform:
    res: None
    cal: test
postprocessor_grid:
    n_estimators: [120, 150, 170, 190,  220, 250] # [50, 100, 200] # [10,30, 50, 70, 100, 120] # 
   # max_depth: [5,6,7,8,10,11,12,13] #[11,12, 13, 14, 15] # [4,6,7,8,9] #[3, 5, 10]
    # min_samples_split: [20, 30, 40, 50] # [2, 5, 10]
    min_samples_leaf:  [110, 120, 130, 140] #[20, 30, 40, 50] # [40,  50, 60 , 70] # [1, 2, 4] [10,  20, 30, 40] 60, 65, 70, 75,  80, 85, 90, 95, 100
    
  # File: transform-test_n-epoch1_n-folds10_probits_predweight_clustering
