name: lda_binning
postprocessor_args:
  temperature: 1.0
  normalize: False
  magnitude: 0.0
  base_scores: ["gini", "margin"]
  n_bins: 10
  alpha: 0.05
  score_type: mean
  bound: hoeffding

experience_args:
  # LDA fitted on res, binning on cal, evaluate on res/cal/test
  n_epochs:
    res: None
    cal: 1
  transform:
    res: None
    cal: test

postprocessor_grid:
  alpha: [0.05, 0.1, 0.5]
  score_type: ["mean", "upper"]
  n_bins: [5, 10, 15, 20, 30]
  base_scores:
    - ["gini", "margin"]
    - ["gini", "msp"]
    - ["gini", "margin", "msp"]
    - ["gini", "margin", "entropy"]
