
name: cifar10
num_classes: 10
pre_size: 32
image_size: 32
split_names: [res, cal, test]
n_samples : 
  res: 0
  cal: 0
  test: 10000
transform:
  res: None
  cal: test
n_epochs:
  res: None
  cal: 1

seed_split : 9
batch_size_train: 252
batch_size_test: 252

