name: cifar10
num_classes: 10
pre_size: 32
image_size: 32
split_names: [res, cal, test]
n_samples:
  res: 1000
  cal: 4000
  test: 5000
transform:
  res: test
  cal: test
n_epochs:
  res: 1
  cal: 1

seed_split: [1, 2, 3, 4, 5, 6, 7, 8, 9]
batch_size_train: 512
batch_size_test: 512
