name: cifar10
num_classes: 10
pre_size: 32
image_size: 32
split_names: [res, cal, test]
n_samples:
  res: 0      # No res split - all labeled data used for hyperparameter selection
  cal: 5000   # Hyperparameter selection
  test: 5000  # Evaluation

transform:
  res: None
  cal: test
n_epochs:
  res: None
  cal: 1

seed_split: [1, 2, 3, 4, 5, 6, 7, 8, 9]
batch_size_train: 252
batch_size_test: 252
