postprocessor_args:
  lambda: 0.8
  temperature: 0.5
  magnitude: 0.0
experience_args:
  n_folds: 3
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test

  # File: transform-test_n-epoch1_n-folds10_probits_predweight_clustering
