name: partition
postprocessor_args:
  alpha: 0.05
  method: mutinfo_opt
  bound: bernstein
  n_classes: 10

  space : probits
  reorder_embs: True
  temperature: 2
  pred_weights: 0
  
  n_clusters: 100
  cov_type: diag
  init_scheme: random
  n_init: 1
  max_iter: 50
  clustering_seed: 1
  lr: 0.0001
  sig: 0.05
  with_logdet: False
  cov_proj_type: squared_clamp_min
  alpha: 0.1
  mutual_computation: decomposed
  
experience_args:
  n_folds: None
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test

