postprocessor_args:
  alpha: 0.05
  method: soft-kmeans_torch
  bound: bernstein
  n_classes: 1000

  space : probits
  reorder_embs: True
  temperature: 2
  pred_weights: 0
  
  n_clusters: 200
  cov_type: diag
  init_scheme: kmeans
  n_init: 1
  max_iter: 500
  clustering_seed: 1
  lr: 0.0005
  sig: 0.001
  
ablation_args:
  method : [soft-kmeans_torch, "mutinfo_opt"] # [kmeans, soft-kmeans, soft-kmeans_torch]
experience_args:
  n_folds: None
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test

# File: fair_ce_results/imagenet_timm_vit_tiny16_r-0.5_seed-split-9/transform-test_n-epoch1_n-folds3_probits_soft-kmeans_torch_bernstein_n-init-10_kmeans_clustering/hyperparams_results_2.csv
