name: margin
postprocessor_args:
  temperature: 1.0
  magnitude: 0.0
experience_args:
  n_folds: None
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test
postprocessor_grid:
  temperature: [0.7, 0.8, 0.9, 1.0, 1.1, 1.2]
