
name: imagenet
num_classes: 1000
pre_size: 242
image_size: 242
split_names: [res, cal, test]
n_samples : 
  res: 12500
  cal: [500, 1000, 3000, 5000, 7000, 9000, 11000, 12500]
  test: 25000
transform:
  res: test
  cal: test
n_epochs:
  res: 1
  cal: 1

seed_split : [1, 2, 3, 4, 5, 6, 7, 8, 9]
batch_size_train: 512
batch_size_test: 512

