
name: imagenet
num_classes: 1000
pre_size: 242
image_size: 242
split_names: [res, cal, test]
n_samples : 
  res: 10000
  cal: 15000
  test: 25000
transform:
  res: test
  cal: test
n_epochs:
  res: 1
  cal: 1

seed_split : [9]
batch_size_train: 512
batch_size_test: 512

