name: partition
postprocessor_args:
  alpha: 0.05
  method: quantile-merge
  bound: hoeffding
  n_classes: 10

  space: gini
  reorder_embs: False
  temperature: 1.0
  magnitude: 0.0
  pred_weights: 0
  score: upper

  n_clusters: 50
  n_min: 50
  init_scheme: None
  n_init: None
  max_iter: None
  clustering_seed: None

experience_args:
  n_folds: None
  fit_after_cv: False
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test

postprocessor_grid:
  n_clusters: [10, 20, 50]
  n_min: [50, 100]
