
name: cifar100
num_classes: 100
pre_size: 32
image_size: 32
split_names: [res, cal, test]
n_samples :
  res: 4000
  cal: 1000
  test: 5000

seed_split : [9]
batch_size_train: 512
batch_size_test: 512
