name: partition
postprocessor_args:
  alpha: 0.05
  method: raw-score
  bound: hoeffding
  n_classes: 100

  space: gini
  reorder_embs: False
  temperature: 1.0
  magnitude: 0.0
  pred_weights: 0
  score: upper

  n_clusters: 1
  n_min: 1
  init_scheme: None
  n_init: None
  max_iter: None
  clustering_seed: None

experience_args:
  n_folds: None
  fit_after_cv: False
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test

postprocessor_grid:
  temperature: [0.7, 0.8, 0.9, 1.0, 1.1, 1.2]
  magnitude: [0.0, 0.002, 0.004, 0.006, 0.008, 0.01, 0.012]
