postprocessor_args:
  n_clusters: 250
  alpha: 0.05
  method: soft-kmeans_torch
  n_classes: 10
  clustering_seed: 1
  init_scheme: kmeans
  n_init: 10
  space : probits
  temperature: 1.5
  cov_type: diag
  reorder_embs: True
  bound: bernstein
  pred_weights: 0
ablation_args:
  temperature:  [2.3, 2.6, 3.3, 3.6, 4.3, 4.6] # [0.8, 0.9, 2, 3, 4, 5, 10, 15] #[1., 1.05, 1.1, 1.15, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]
  n_clusters:  [450, 550, 650] #[10, 30, 50, 70, 90, 110, 130, 360, 400, 500, 600, 700]  #[150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330]
experience_args:
  n_folds: 10
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test
  
  
# File: fair_ce_results/imagenet_timm_vit_base16_r-0.5_seed-split-9/transform-test_n-epoch1_n-folds3_probits_soft-kmeans_torch_bernstein_n-init-10_kmeans_clustering
