name: partition
postprocessor_args:
  alpha: 0.05
  method: decision-tree
  bound: bernstein
  n_classes: 100

  space : probits
  reorder_embs: True
  n_dim: 1
  temperature: 1.
  pred_weights: 0
  
  n_clusters: 78
  init_scheme: None
  n_init: None
  max_iter: None
  clustering_seed: 3
  calibrate: False
  
  
experience_args:
  ratio_res_split: None
  n_split_val : None
  weight_std : None
  n_folds: 4
  fit_after_cv: True
  n_epochs:
    res: 1
    cal: 1
  transform:
    res: test
    cal: test

postprocessor_grid:
  n_clusters: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30] #100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 
  temperature: [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45, 1.5, 1.55, 1.6, 1.65, 1.7, 1.75, 1.8, 1.85, 1.9, 1.95, 2.0] #1, 2, 3, 3.5, 5, 4.5, 5.,
